name: Generate report

on:
   push:
     branches:
       - '**'
     paths:
       - 'p*/**'
   workflow_dispatch:

jobs:
  generate:
    runs-on: 'self-hosted'
    container:
      image: tobiichi3227/tps-github-runner:latest
      options: --user root
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Allow Git to access workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check Progress
        uses: tobiichi3227/tps-actions/.github/actions/check-progress@dev
        with:
          report-path: report.md

      - name: Count total subtasks
        id: count
        run: |
          total=$(find p*/subtasks.json | xargs jq '[.subtasks[]] | length' | paste -sd+ - | bc)
          echo "total=$total" >> $GITHUB_OUTPUT

      - name: List Subtasks
        uses: TNFSH-Programming-Contest/tps-actions/.github/actions/list-subtasks@main
        with:
          report-path: report.md

      - name: List Scores
        uses: blameazu/tps-actions/.github/actions/list-scores@main
        with:
          report-path: report.md
          group-size: ${{ steps.count.outputs.total }}

      - name: Debug report.md
        run: |
          echo "====== report.md content ======"
          cat report.md
          echo "====== git diff ======"
          git diff report.md

      - name: Commit files
        run: |
          git add report.md
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull
          git diff-index --quiet HEAD -- || git commit -m "Generate report"
          git push